### ISSUE TITLE
Module to handle mnemonics

### ISSUE THREAD

**Issue by ligi** [walleth/kethereum#3]

**Comment by mirceanis** [comment]
Hello,

I want to submit a PR for this but have a question regarding the project layout.
Handling mnemonics is basically supporting bip32 and bip39, but it also ties in to the already existing module BIP44.
IMO the best place for this new code to sit is in the `crypto` module because it involves working with some code from `Keys.kt` and `Sign.kt` but because of the above mentioned link it would also make the `crypto` module depend on `BIP44`.

Of course, it can add it as its own module but it just seems to be missing its spot.

How flexible is the project layout?

**Comment by ligi** [comment]
> I want to submit a PR for this

YAY


> Handling mnemonics is basically supporting bip32 and bip39, but it also ties in to the already existing module BIP44.
>IMO the best place for this new code to sit is in the crypto module because it involves working with some code from Keys.kt and Sign.kt but because of the above mentioned link it would also make the crypto module depend on BIP44.

Did not yet look that deep into mnemonics - but I think there should be a module BIP-32 that depends on BIP-44 and crypto - don't you think this would work? Would love to avoid putting it in crypto as I like small modules - unix style

> How flexible is the project layout?

can you elaborate what you mean? I want it to be as flexible and modular as possible - if you have ideas - shoot!

**Comment by mirceanis** [comment]
Thanks,
I'll add it as its own module then, with a sprinkle of changes to the other modules as needed.

**Comment by ligi** [comment]
Sounds great - happy coding!-)

**Comment by ligi** [comment]
@mirceanis totally forgot - might also be interesting to @rmeissner and @fmrsabino - they already have a implementation with kethereum dependencies in their repo: https://github.com/gnosis/heimdall-android/tree/master/mnemonic - just not a big fan of having the wordlists in memory all the time there - but perhaps it could share some tests or ideas.

**Comment by rmeissner** [comment]
Yeah, we planned to refactor and test our implementation and then also provide a PR. But of course we are happy to take another implementation ;). 

Concerning dependencies to bip32/bip44: imo bip39 is only to generate a seed from a mnemonic. That seed then is used to generate the root node that you can use to derive the children nodes with bip32/bip44. We kept these in different modules in our project, so that we can move small parts to other projects.

**Comment by rmeissner** [comment]
Currently the only open issue is to load the wordlist only when needed, right?

I would propose to make bip32 and bip39 two different modules (since bip32 is not about mnemonics).

Another question for me is what is the best way to handle spongycastle with proguard. Since some of the crypto algorithms used by bip39 are only available through spongycastle and we use a provider to load them we need to exclude everything from spongycastle from proguard (which I really don't want to do). In our project we directly use the spongy castle implementations (therefore we can use proguard and obfuscation since they are directly referenced). I know this might not make sense for other platforms (and maybe upcoming android versions where this is not needed).
